<a href="https://colab.research.google.com/github/Dipali-Jadhav14/API_CALLING/blob/main/Data_Cleaning_with_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#load dataset:

'''
content/movie_titles_metadata.tsv'
/content/aug_train (1).csv

In [ ]:
'''
will see some parameters used in csv files
'''

In [ ]:
pd.read_csv('/content/movie_titles_metadata.tsv')

    m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0    m1\t1492: conquest of paradise\t1992\t6.20\t10...
1    m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2    m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3    m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4    m5\tthe fifth element\t1997\t7.50\t133756\t['a...
..                                                 ...
611  m612\twatchmen\t2009\t7.80\t135229\t['action' ...
612  m613\txxx\t2002\t5.60\t53505\t['action' 'adven...
613  m614\tx-men\t2000\t7.40\t122149\t['action' 'sc...
614  m615\tyoung frankenstein\t1974\t8.00\t57618\t[...
615  m616\tzulu dawn\t1979\t6.40\t1911\t['action' '...

[616 rows x 1 columns]

In [ ]:
#sep parameter:

#sep means the symbol used to split the data in the file.

'''
1)Colon-separated file (:)
2)sep="--")
3)Pipe-separated file (|)
4)Multiple spaces as separator

If data is separated by many spaces:
  pd.read_csv("data.txt", sep="\s+")

5)Comma-separated file (Default)
'''


pd.read_csv('/content/movie_titles_metadata.tsv',sep='\t')

<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:12: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2418157317.py:12: SyntaxWarning: invalid escape sequence '\s'
  pd.read_csv("data.txt", sep="\s+")

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [ ]:
#names:
pd.read_csv('/content/movie_titles_metadata.tsv',sep='\t',names=['SNO','Names','Released_date','rating','votes','genre'])

,SNO,Names,Released_date,rating,votes,genre
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [ ]:
pd.read_csv('/content/aug_train (1).csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
#index_col parameter:

#tells pandas which column should be used as the index

pd.read_csv('/content/aug_train (1).csv',index_col='enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
#Header parameter:  (IMP)
#First row contains column names (default)
#Tell pandas to NOT treat any row as header:

pd.read_csv('/content/test.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [ ]:
pd.read_csv('/content/test.csv',header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [ ]:
#use_col parameter:
#Which columns you want to read from the file
#It helps you load only selected columns, instead of loading the entire file.

pd.read_csv('/content/aug_train (1).csv',usecols=['enrollee_id','gender','education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

In [ ]:
#sqeeze parameter:
#used to convert a DataFrame with one column into a Series automatically.

ser = pd.read_csv('/content/aug_train (1).csv', usecols=['gender']).squeeze("columns")
print(ser)
type(ser)

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: object

pandas.core.series.Series

In [ ]:
#skip_rows/nrows:
#used to skip specific rows while reading a file

pd.read_csv('/content/aug_train (1).csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
pd.read_csv('/content/aug_train (1).csv',skiprows=[0,1])

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
#used to read only a limited number of rows from the file.

pd.read_csv('/content/aug_train (1).csv',nrows=50)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
6,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
7,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
8,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
9,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0
10,29452,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,2,NaN,NaN,never,32,1.0
11,23853,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,5000-9999,Pvt Ltd,1,108,0.0
12,25619,city_61,0.913,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,1000-4999,Pvt Ltd,3,23,0.0
13,5826,city_21,0.624,Male,No relevent experience,NaN,NaN,NaN,2,NaN,NaN,never,24,0.0
14,8722,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,5,NaN,NaN,never,26,0.0
15,6588,city_114,0.926,Male,Has relevent experience,no_enrollment,Graduate,STEM,16,10/49,Pvt Ltd,>4,18,0.0
16,4167,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,never,106,0.0
17,5764,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,2,5000-9999,Pvt Ltd,2,7,0.0
18,2156,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,7,10000+,Pvt Ltd,never,23,1.0
19,11399,city_13,0.827,Female,Has relevent experience,no_enrollment,Graduate,Arts,4,NaN,NaN,1,132,1.0
20,31972,city_159,0.843,Male,Has relevent experience,no_enrollment,Masters,STEM,11,100-500,Pvt Ltd,1,68,0.0
21,19061,city_114,0.926,Male,Has relevent experience,no_enrollment,Masters,STEM,11,100-500,Pvt Ltd,2,50,0.0
22,6491,city_102,0.804,NaN,Has relevent experience,no_enrollment,Masters,STEM,10,NaN,NaN,1,48,0.0
23,7041,city_40,0.776,Male,Has relevent experience,no_enrollment,Graduate,Humanities,<1,1000-4999,Pvt Ltd,1,65,0.0
24,22767,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,5,1000-4999,Pvt Ltd,1,13,0.0
25,14505,city_67,0.855,NaN,No relevent experience,no_enrollment,High School,NaN,4,NaN,NaN,never,22,0.0
26,17139,city_21,0.624,NaN,Has relevent experience,Part time course,Graduate,STEM,14,500-999,Pvt Ltd,1,148,1.0
27,28476,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,Arts,5,NaN,NaN,2,72,0.0
28,21538,city_100,0.887,Male,Has relevent experience,no_enrollment,High School,NaN,11,<10,Pvt Ltd,1,8,1.0
29,10408,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,18,50-99,Funded Startup,2,68,1.0
30,14928,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,100-500,Pvt Ltd,3,40,0.0
31,22293,city_103,0.920,Male,Has relevent experience,Part time course,Graduate,STEM,19,5000-9999,Pvt Ltd,>4,141,0.0
32,4324,city_103,0.920,Female,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,1,24,0.0
33,26966,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,>20,100-500,Pvt Ltd,>4,82,0.0
34,26494,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,Business Degree,12,5000-9999,Pvt Ltd,3,145,0.0
35,4866,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,10,10/49,Early Stage Startup,2,206,0.0
36,12726,city_114,0.926,Male,No relevent experience,Part time course,High School,NaN,1,10000+,Other,1,152,0.0
37,10164,city_114,0.926,Male,Has relevent experience,no_enrollment,Phd,STEM,>20,100-500,Pvt Ltd,4,42,1.0
38,8612,city_103,0.920,NaN,No relevent experience,no_enrollment,Graduate,STEM,12,NaN,NaN,4,50,0.0
39,24659,city_71,0.884,Male,No relevent experience,no_enrollment,NaN,NaN,3,NaN,NaN,never,106,0.0
40,2547,city_114,0.926,Female,Has relevent experience,Full time course,Masters,STEM,16,1000-4999,Public Sector,2,14,0.0
41,13854,city_104,0.924,Male,Has relevent experience,no_enrollment,High School,NaN,4,10/49,Pvt Ltd,2,36,0.0
42,31654,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,50-99,Early Stage Startup,1,112,1.0
43,13643,city_64,0.666,NaN,No relevent experience,no_enrollment,Graduate,No Major,9,50-99,Pvt Ltd,never,108,0.0
44,5590,city_21,0.624,Male,Has relevent experience,Part time course,Masters,STEM,9,5000-9999,Pvt Ltd,3,7,1.0
45,22452,city_21,0.624,Female,No relevent experience,Full time course,Masters,STEM,5,NaN,NaN,never,26,1.0
46,9006,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,100-500,Pvt Ltd,never,87,1.0
47,25987,city_103,0.920,Other,Has relevent experience,no_enrollment,Graduate,STEM,19,10000+,Public Sector,4,52,1.0
48,4476,city_101,0.558,Male,Has relevent experience,no_enrollment,Graduate,No Major,15,NaN,NaN,>4,20,1.0
49,25103,city_83,0.923,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,10/49,Pvt Ltd,1,21,0.0

In [ ]:
'''
Categorical Encoding Methods

Common Encodings Used

1️UTF-8 (most common, default)

Latin-1 (ISO-8859-1) (avoids many errors)

cp1252 (Windows encoding)

UTF-16 / UTF-32 (for some text-heavy files)
'''

In [ ]:
#encoding parameter:

#how the text in the file is stored (character format/language format).
import pandas as pd

pd.read_csv('/content/zomato.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 7044: invalid continuation byte

In [ ]:
pd.read_csv('/content/zomato.csv',encoding='latin_1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [ ]:
import pandas as pd

In [ ]:
#dtype:
#Dtype: set the data type of one or more columns while reading a file

pd.read_csv('/content/aug_train (1).csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
pd.read_csv('/content/aug_train (1).csv',dtype={'target':int})

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0

In [ ]:
#handling dates:
import pandas as pd

#convert a column (or multiple columns) into proper datetime format while reading the file.
pd.read_csv('/content/IPL Matches 2008-2020.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [ ]:
pd.read_csv('/content/IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [ ]:
#convertor:
#change / modify / clean / format a column as it is being loaded.
pd.read_csv('/content/IPL Matches 2008-2020.csv')

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
def rename(name):
  if name=='Royal Challengers Bangalore':
    return "RCB"
  else:
    return name
rename('Royal Challengers Bangalore')

'RCB'

In [ ]:
pd.read_csv('/content/IPL Matches 2008-2020.csv',converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
#working with Excel file:
import pandas as pd
pd.read_excel('/content/Output.xlsx')

   Rno   Name
0    1    Jay
1    2    Raj
2    3  Baman
3    4   Saya
4    5    Sai

In [ ]:
import pandas as pd
#To remove 0th index column from dataset we use index_col parameter
df = pd.read_excel('/content/Output.xlsx', index_col=0)

In [ ]:
df

      Name
Rno
1      Jay
2      Raj
3    Baman
4     Saya
5      Sai

In [ ]:
#To load next/another sheet data we use seetname parameter....by default it will open sheet1..To open another sheet within same excel file pass
#parameter sheet_name
pd.read_excel('/content/Output.xlsx',sheet_name='Sheet2')

   Cid Cname
0  101     A
1  102     B
2  103     C

In [ ]:
#chunksize:It loads the file piece-by-piece, not all rows together.

dff=pd.read_csv('/content/aug_train.csv',chunksize=5)

dff

In [ ]:

for chunks in dff:
  print(chunks.shape)

(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)
(5, 14)

In [ ]:
pd.read_csv('/content/question_bank.tsv')

                                  question_id\tquestion
0                                              Q00001\t
1     Q00002\ta total cholesterol of 180 to 200 mgdl...
2     Q00003\tabout how many years experience do you...
3     Q00004\taccording to anima the bible or what o...
4     Q00005\tae you looking for examples of septic ...
...                                                 ...
3936  Q03937\twould you want to buy flame design sti...
3937  Q03938\twould you want to know about ron howar...
3938  Q03939\twould you want to know credit report s...
3939  Q03940\twould you want to know what is in a cr...
3940  Q03941\twould you wanting to know how to set o...

[3941 rows x 1 columns]

In [ ]:
#read text files:
pd.read_csv('/content/question_bank.tsv',sep='\t')

     question_id                                           question
0         Q00001                                                NaN
1         Q00002  a total cholesterol of 180 to 200 mgdl 10 to 1...
2         Q00003  about how many years experience do you want th...
3         Q00004  according to anima the bible or what other source
4         Q00005  ae you looking for examples of septic system d...
...          ...                                                ...
3936      Q03937        would you want to buy flame design stickers
3937      Q03938  would you want to know about ron howards actin...
3938      Q03939        would you want to know credit report scores
3939      Q03940  would you want to know what is in a credit report
3940      Q03941        would you wanting to know how to set one up

[3941 rows x 2 columns]

In [ ]:
import pandas as pd

df = pd.read_json('/content/train.json')   # For Colab
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
'''
Pandas Export:
•	to cvs
•	to excel
•	to html
•	to json
•	to sql


'''

'\nPandas Export:\n•\tto cvs\n•\tto excel\n•\tto html\n•\tto json\n•\tto sql\n\n\n'

ParserError: Error tokenizing data. C error: Expected 21 fields in line 10331, saw 23

In [ ]:
#to_csv:
import pandas as pd
df=pd.read_csv('deliveries.csv')#it creates empty dataframe

df.head()

ParserError: Error tokenizing data. C error: Expected 21 fields in line 10331, saw 23